### ISSUE TITLE
user story 1 / art pieces list

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#1]
## user story 1 / art pieces list

As an art enthusiast
I want to see all art pieces of the artist
to be able to get an overview of his skills

## Description
![Bildschirmfoto 2023-08-11 um 16 51 32](https://github.com/alper92/capstone-project/assets/83625276/798c3035-9188-4e17-b983-3f05d9b69844)

## Acceptance criteria
- [x] a header with a slogan is visible at the very top of the page
- [x] vertical list of all art pieces is visible
- [x] you can vertically scroll to see all art pieces
- [x] every image can have different sizes but is fitting in the screen of the app
- [x] the art piece name is visible at the bottom of the picture

## Tasks
- [x]  create a branch with suitable name
- [x]  create a component Header with the artist name and the slogan
- [x]  create a component ArtPiecesPreview in index.js which contains the name of the art piece 
- [x] map over the initial array of art pieces to display each preview underneath each other
- [x] add the expected styling (size, image)
- [x] test: do all images render properly?
