### ISSUE TITLE
user story 6 / convert images when uploading

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#10]
## Value proposition

As an art enthusiast
I don't want to wait that long until all pictures are visible
In order to look through all pictures quickly

## Description
There is no wire-frame for that since you need to enhance the file upload function which is already existing.

## References:
References: 
- for keeping aspect ratio when resizing and trying out things: https://andrew.hedges.name/experiments/aspect_ratio/
- how the file reader basically works: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/FileReader
- how i found out that you have to redraw the picture in canvas to convert it to webp and compress it: https://yaz.in/p/blobs-files-and-data-uris/
- in the very end of this article it shows an example similar to mine with resizing and compression https://labs.madisoft.it/javascript-image-compression-and-resizing/

## Acceptance criteria

- [x] when the admin uploads any picture in any file size the image will be converted to webp, resized and compressed
- [x] if the upload image is already a webp-file, after uploading it should remain a webp file but only be compressed if to big
- [x] the quality of the images should be still acceptable with no recognizable pixelation
- [x] the pictures of the artist are smartphone which are never smaller then 100KiB (edit: since my last story after the research task did not make sense)

## Tasks

- [x] create a new branch called `feat/convert-images-when-uploading`
- [x] read about compression and dataURLs for images and find out how the file size and the quality behave when compressing, converting to different formats
- [x] enhance the `handleImageUpload'-function so, that you will achieve the points in the acceptance criteria

## Size

L

**Comment by F-Kirchhoff** [comment]
I like that you included the research as a task 👍
