### ISSUE TITLE
user story 7 / create sharing functionality

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#11]
## Value proposition

As an art enthusiast
I want to to share pictures I liked
In order to show other people the art and discuss it on social networks

## Description
![Bildschirmfoto 2023-08-21 um 07 31 33](https://github.com/alper92/capstone-project/assets/83625276/784e570d-e954-46bb-b1cd-925ee21d6114)

## Acceptance criteria

- [x] When clicking the share button you can share the art piece on different social network platforms like (facebook, and instagram)
- [x] When clicking the share button there should be a modal to decide on which social network you want to share the art piece with (EDIT: since there are only 2 social networks needed it was not needed to create a modal!)

## Tasks

- [x] create a branch called `feat/sharing-functionality`
- [x] go to `[slug].js` page then add and import  Head component from next.js
- [x] create meta data in the Head-Component with the desired information (for now the`description`, `name`)
- [x] install react share library and next share to compare both (https://www.npmjs.com/package/next-share) / https://www.npmjs.com/package/react-share
- [x] compare both and decide which package makes more sense
- [x] implement share buttons with the the information given in the docs 

## Size

M

**Comment by MiejkeHoltermann** [comment]
I think "doing research" should not be in your user story. You should already have a vague idea how you want to implement the sharing functionality.

**Comment by alper92** [comment]
> * go to the details slug page and add head component with meta data

Thank you for your review. I also thought it is not possible. In my previous user-story the coach even liked it, that I have research in my tasks.
