### ISSUE TITLE
user story 8 / navigation part 2

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#15]
## Value proposition

As an art enthusiast 
I want to scroll up back to the navigation quickly and also come back to the last point after visiting the details page
in order to navigate easier through the gallery and to not loose orientation 

## Description
![Bildschirmfoto 2023-08-25 um 01 37 31](https://github.com/alper92/capstone-project/assets/83625276/5d81e962-885e-4ae8-9b86-1ff0cc024401)

## Acceptance criteria

- [x] clicking on one of the categories should be visible with changing and maintaining the background color
- [x] when creating a new category you should not adjust the code!
- [x] on the very bottom of the page there should be an arrow up button which will scroll up back to the navigation
- [x] the arrow up button should only appear when there is a scrolling  activity
- [ ] when clicking on the back button from the details page the gallery should route back close to the selected picture

## Tasks

- [x] create a branch called `navigation-part-2`
- [x] go to the `CategoryFilter` Component create a state and give props to the buttons to maintain the color HINT: look at the `uniqueCategories`-array and make it work without touching the code when creating new categories
- [x] create a button with a fixed position on the right downside of the screen, use the `scrollPercent` variable to make the button appear and set an anchor to the navigation to have a `scroll-back-point`
- [ ] use the scroll percentage of the progress bar to find the scroll point when coming back (This is just an Idea how to solve it)

## Size

L

**Comment by dm-nosov** [comment]
LGTM!
