### ISSUE TITLE
user story 9 / cropping images

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#16]
## Value proposition

As an administrator 
I want to to be able to zoom and  rotate the pictures before finally adding them to the gallery
in order to give my gallery visitors a better experience

## Description

![Bildschirmfoto 2023-08-25 um 00 38 03](https://github.com/alper92/capstone-project/assets/83625276/a9e05c6e-b459-43b7-a7d9-88afb1460beb)

## Acceptance criteria

- [x] after uploading the image the editing window should open up to zoom and rotate the art piece
- [x] zooming makes it possible to zoom in 
- [x] rotate should make it possible to rotate the picture
- [x] after editing the picture it should be saved in the `fileImageUrl`-state in order to afterwords add name, category description for the final adding of the cropped image

## Tasks

- [x] create a branch called `image-cropping`
- [x] create the component cropper
- [x] install `react-easy-crop` package
- [x] read your bookmarks, articles about react-easy-crop integration carefully and start implementing it slowly and step by step

## Size
L
