### ISSUE TITLE
user story 10 / admin login

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#17]
## Value proposition

As an administrator
I want that the admin area is protected from visitors 
in order to protect all of my images which are shown in the gallery

## Description
![Bildschirmfoto 2023-08-27 um 13 41 02](https://github.com/alper92/capstone-project/assets/83625276/44f3d951-d5a7-4e96-8ed2-6faead8d3185)

## Acceptance criteria

- [x] when going to the admin page there should be a login modal with a `username` and a `password`
- [x] when submitting the wrong password or username there should be message shown with "wrong username or password"
- [x] after submitting the correct password and username the admin area opens up to be able to administrate all images
- [x] the gallery is visible for all users
- [x] the administration is not visible for unauthorized users
- [x] the administrator should be able to log out

## Tasks

- [x] create a branch called `admin-login`
- [x] install the package `next-auth` / `"next-auth": "^4.23.1"`
- [x] go to `_app.js` and import the `SessionProvider` and wrap the `SessionProvider`-Tag around the `<Component />` Tag
- [x] look at the example Repo on Slack for further steps all in all there are `4-Commits` which describe the procedure

## Size
L

**Comment by izabelladobielewska** [comment]
Looks good:)
