### ISSUE TITLE
user story 11 /  implement database

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#19]
## Value proposition

As an adminstrator
I want all of my pictures stored in a cloud
In order to make my new uploaded pictures visible for everyone

## Description
No Scribble here, since there is only code which must be written to integrate a database with mongoose / mongoDB.

## Acceptance criteria

- [x] the app is able to make all CRUD operations using mongoDB / mongoose
- [x] after uploading images the images are visible for all users (no local storage)
- [x] for now every one can write, read and update the database (later there will be an authorisation for only visitors and admins)

## Tasks

- [x] create a branch called `integrate-database`
- [x] create a database in mongoDB Atlas called `capstone-project`
- [x] look in the session documentations and especially in `recap-6` to create api-routes for the desired requests (`put`, `patch`, `get` ect.)
- [x] write a `scheme` and add the `connector.js`
- [x] all the setterFunctions are in `admin.js` look there to reach your goal

## Size
XL

**Comment by NicoleHoerner** [comment]
Hi there!
Setting up the mongoDB database looks ok.
Should the images/pictures just be stored and visible for others or are people also be able to upload art?
When it comes to images you might consider something like Cloudinary which enables users to upload, store, manage, manipulate, and deliver images.
It is just a suggestion, as I have read that there might be some issues with loading time, searchability, compressibility, manipulations are not easy... - I don't know how far you thought about it.

**Comment by alper92** [comment]
Thank you very your comment. First of all you are absolutely right. I am taking a very big risk here, with my Fileupload.
I know, that when the side is online, for sure Image-Manipulations won't work exactly the same way as with cloudinary image upload. With cloudinary you are much more flexible. In the end of the day I have a base64 string saved in a database as a string as well. During the Fileupload the image will be resized, compressed and converted in to a webp-format. After uploading the size range is between 70 to 180kb. The compression converting etc. already works just fine. Some people even uploaded an 8mb file and a 89kb file came out and the image still looke ok. This point still gives me hope to not give up on my file upload and keep on going. In worst case, I'll implement cloudinary and change the whole plan. For only this task I gave my self the whole upcoming week time. Let's hope for the best and thank you for your concern!
