### ISSUE TITLE
user story 2 / art piece details page

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#2]
## Value proposition

As an art enthusiast
I want to be able to see the full art piece with detail information
so that I can learn everything about the piece

## Description
![Bildschirmfoto 2023-08-14 um 09 37 08](https://github.com/alper92/capstone-project/assets/83625276/7c7966b0-8460-4f09-a36c-515c1d73e1ea)

## Acceptance criteria

- [x] clicking an art piece from the art pieces list shows the detail page
- [x] each details page shows the header with the slogan 
- [x] the art piece image is displayed in the middle the browser window
- [x] the art piece title is displayed
- [x] the art piece year is displayed
- [x] the art piece category is displayed
- [x] the art piece technic is displayed
- [x] a back-button is displayed
- [x] clicking the back-button shows the list view again

#### Tasks

- [x] add the header component with the slogan to the top
- [x] create the button which will go back to the art pieces list above the title
- [x] create the component `ArtPieceDetails`
- [x] `ArtPieceDetails` props: `image`, `title`, `year`, `category`, `technic`, `description`
- [x] create the page `pages/art-pieces/[slug]` that renders `ArtPieceDetails`
- [x] read the query parameter `slug` from `next/router`
- [x] use the `slug` to find the art piece to display

**Comment by ninaassmann** [comment]
- In the task section, there is the button missing
- In acceptance criteria you could also add where the user can finde the back button, maybe you better move the button above the title, but thats just an idea

**Comment by alper92** [comment]
@ninaassmann: Thanks a lot. I'll move the button above the title it is better to navigate then.
