### ISSUE TITLE
user story 12 / feat-darkmode

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#20]
## Value proposition

As an art enthusiast
I want to be able to switch between light and dark mode
In order to watch the pictures in the night without getting disturbed by the white background

## Description
![Bildschirmfoto 2023-08-28 um 08 01 53](https://github.com/alper92/capstone-project/assets/83625276/ce60e621-d460-4bcb-87f0-db9d41a5a0db)

## Acceptance criteria

- [x] there is a button on the right side of the header which enables disables dark mode
- [x] when pressing the button the color theme is going to change to darker colors
- [x] the enabling and disabling of the theme should work for all sites
- [x] the background color should switch to a color near black and the text-colors should switch to white
- [x] the darkmode should be also enabled if your browser is in darkmode

## Tasks

- [x] create a branch called `feat-darkmode`
- [x] create a button component called `DarkmodeSwitch` which will handle the theme switch to darkmode
- [x] access the root colors in `_app.js` with defining an object called `theme` and store in a state and pass it to all components and sites
- [x] do research and find out how the darkmode can be automatically triggered by the darkmode settings of an users browser

## Size

M
