### ISSUE TITLE
user story 13 / category-statistics

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#23]
## Value proposition

As an art and enthusiast and as an administrator
I want to see category statistics
in order to have a more sorted overview

## Description
<img width="310" alt="Bildschirmfoto 2023-09-01 um 15 00 36" src="https://github.com/alper92/capstone-project/assets/83625276/29f4413f-71f6-48f9-a406-c7a31085a22a">

<img width="331" alt="Bildschirmfoto 2023-09-01 um 14 59 47" src="https://github.com/alper92/capstone-project/assets/83625276/9fb9d1a4-6289-4f2e-bace-f54f097be99f">

## Acceptance criteria

- [x] the amount of all pictures for each clickable category buttons are visible
- [x] they automatically adjust when uploading editing new pictures or categories
- [x] when clicking the editing pen the edit form should toggle for each art piece (side issue)
- [x] adjust all loading screens also for the `CategoryFilter` component / currently it shows the loading button after the categories "New" and "All" (side issue)
- [x] to rapidly go up when editing pictures after an amount of `scrollPercentage` there should be the arrow up button visible 
- [x] the `scrollPercentage` should not stuck when switching the pages (side issue)

## Tasks
- [x] create a branch called `feat/statistics`
- [x] iterate through the art pieces to get an `array.length()` of each category
- [x] adjust the `CategoryFilter`-Component to make the array lengths flexible
- [x] choose a suiting/comfortable `scrollPercentage`-value to display the arrow up button for the `admin.js`-page
- [x] some loading screens are out of the screen due to the wrapped `<main>-Tag` -> choose a better way
- [x] give the `scrollPercentage`-state the value `0` when switching the pages

## Size
L
