### ISSUE TITLE
user story 14 / back-up-light

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#24]
## Value proposition

As an administrator 
I want to be able to store each picture separatly and all of my pictures at once
In order to have a back up on my hard disc

## Description
![Bildschirmfoto 2023-09-01 um 16 02 50](https://github.com/alper92/capstone-project/assets/83625276/87e59339-9927-4b32-b930-8b36b4640f01)

## Acceptance criteria

- [x] after opening up the edit form there should be a download button for each art piece visible
- [x] after clicking each button the art piece image file in the converted `webp`-format should be savable on the hard drive
- [x] when re-uploading the back up image through the `Add new art piece`-form the compression and the converting should be ignored/skipped
<del>- [ ] the `BackUpButton` is visible underneath the `AdminCategoryFilter`-Component </del>
<del>- [ ] after clicking the `BackUpButton` there should be a modal with a final download confirmation </del>
<del>- [ ]  the art pieces should be stored as a `.zip`-file or compressed file </del>
<del>- [ ] the confirmation shows the complete file size</del>

## Tasks

- [x] create a branch called `back-up-light`
- [x] read and do research about how to create a download function (https://stackoverflow.com/questions/14011021/how-to-download-a-base64-encoded-image)
- [x] use the `fileImageUrl`-State to create a download button for each art piece which will throw out the `webp`-file immediatly
- [x] go to `admin.js` and adjust the file upload algorithm to ignore `webp`-files

## Size
<del>XL</del>
S

**Comment by milodevhh** [comment]
That's a large one, but looks fine for me. Have fun with that.
