### ISSUE TITLE
user story 16 / front-end

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#28]
## Value proposition

As an art enthusiast 
I want to to read something about the artist
In order to get to know him a bit better

## Description
![Bildschirmfoto 2023-09-04 um 15 56 05](https://github.com/alper92/capstone-project/assets/83625276/7f377676-c867-43d5-b375-b4533f9d8db2)

## Acceptance criteria

- [x] there is a greeting next to the artist image
- [x] there is a short about text about the artists art
- [x] there is a headline to select a category
- [x] there is a footer with a share button for the website (facebook und whatsapp share)
- [x] there is a link to the imprint page and the privacy policy
- [x] both links lead to a separate side which contain a back button/link to the gallery (`index.js`)
- [x] the pages themselves should contain some sample text with paragraphs, headings, and 
- [x] both pages do not contain a footer only the back button/link
- [x] the footer is not visible in the `admin.js`

## Tasks

- [x] create a branch called `front-end`
- [x] create the about area with the greeting as a css grid
- [x] create a heading for the categories
- [x] create a footer component 
- [x] place the arrow up button inside of the footer component on the right
- [x] create a flex-box for the share buttons, the links and the arrow up button
- [x] create a new pages for  `Imprint` and `Privacy Policy`

## Size
S
