### ISSUE TITLE
ux user story / improve-ux

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#32]
## Value proposition

As an admin and art enthusiast
I want to navigate better and don't want to get irritated by the pogressbar
In order to have a better user experience

## Description

![Bildschirmfoto 2023-09-05 um 09 46 55](https://github.com/alper92/capstone-project/assets/83625276/81b91768-acc7-4660-b92f-866b899f1f63)
![Bildschirmfoto 2023-09-07 um 08 29 59](https://github.com/alper92/capstone-project/assets/83625276/329e0a64-2d80-4b96-b33e-e1efdda203fd)

## Acceptance criteria

- [x] since it was not possible to fix the scroll preservation from user story #12 there should be a grid selector to be able to show art pieces in different grid sizes to navigate better back from the gallery filter
- [x] if the name and date wont fit to the small art piece preview it is accepted to not render the name and date in the tiny view
- [x] the grid should only appear if the `CategoryFilter` is `active`
- [x] when cropping pictures the cancel button should not reset the cropping it should just cancel to start the cropping over again
- [x] when cropping there should be a reset button in order to fully start new with a new art piece to upload
- [x] the progress bar does not stuck when coming back from the details page or vice versa (still not fixed even going successfull through QA)
- [x] when adding a new art piece the form should be preserved exactly as the image to crop
- [x] fix all `Lighthouse` errors or warnings in order to keep a good performance of the app

## Tasks

- [x] create a branch called `improve-ux`
- [x] look at the css command `grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));` with giving the 280px different sizes with a state through props in the css and buttons which will set the min sizes you are able to manipulate the grid (HINT: Try to work first with those pixel sizes -> `50px` (small) / `100px` (middle size) / `280px` (large size)
- [x] you can conditionally render the `name` and `date` of the `ArtPiecesPerview`-Component with the `size`-State

## Size
M
