### ISSUE TITLE
user story 3 / add-pictures-as-admin

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#4]
## Value proposition

As a administrator
I want to be able to upload my new paintings
In order to keep my audience on track

## Description
![Bildschirmfoto 2023-08-15 um 01 04 21](https://github.com/alper92/capstone-project/assets/83625276/a6f17f7a-df23-422e-928c-146709ac0fe5)

## Acceptance criteria
- [x] when entering `index.js/admin` you should be able to add pictures (for now it is enough when the administration is reachable via typing it manually in the browser) it should be hidden from the visitors
- [x] fields with labels  for `imageUrl`, `name`, `category`, `technique`, sizes and `description` are visible, accessable 
- [x] after pressing the add button, the new image is shown in the `ArtPiecesPreview` (for now you can only upload images from "pixabay")
- [x] after submitting the newest upload is visible on the very top but below the form as a list
- [x] the list will contain the miniature picture of the art pieces the name and some space on the right (you are going to need that space later for editing and deleting art pieces)
- [x] the name should be transformed in to the slug form with dashes and no spaces, even when typing special letters
- [x] the submit should not be possible when the slug already exists, there should be an immediate information output

## Tasks

- [x] create a branch called `feat/admin`
- [x] create a page called `admin` in the pages folder
- [x] create a component `AddArtPieceForm` and place it in `admin.js` there the form submit will be handled
- [x] create a button which will submit the form data to the `artPieces`-Array with Objects
- [x] handle the name key to convert it to a slug and save it in the array with objects as a slug
- [x] create a component `ArtPiecesListPreview` which will return all art-pieces as a list and the newest on top
- [x] make it visible underneath the form with the newest upload at the top

**Comment by DorisW3** [comment]
Hi Alper,
don't you fetch the image from pixabay, instead of uploading it? 
I like the many details.

**Comment by alper92** [comment]
> Hi Alper, don't you fetch the image from pixabay, instead of uploading it? I like the many details.

@DorisW3: Hi, currently I do not fetch data from pixabay.
