### ISSUE TITLE
user story 4 / edit and delete pictures as admin

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#7]
## Value proposition

As a admin
I want to be able to edit and delete pictures
In order to be be able to fully administrate all of my pictures

## Description
![Bildschirmfoto 2023-08-16 um 15 44 14](https://github.com/alper92/capstone-project/assets/83625276/34efdf1e-2684-433e-9121-634bd6338910)

## Acceptance criteria

- [x] when clicking the pen (`button` which will trigger the editing handler) of a desired item in the list you can edit the selected art piece in a form
- [x] after editing you can press the update button to submit the changes
- [x] when clicking the dustbin (`button` which will trigger the delete handler) there should be a dialogue with a final question for deleting
- [x] all of the edits are visible in the `ArtPiecePreview`(Gallery).

## Tasks

- [x] create a branch called `feat/add-and-delete-artpieces`
- [x] create a handlerFunction for edit in "admin.js" (Pen Button)
- [x] create a handlerFunction for delete in "admin.js" (Dustbin Button)
- [x] build the modal for the user confirmation dialogue

## Size
L

**Comment by CJAkkuec** [comment]
The tasks should probably include mention of your feature branch, the button components that trigger the respective function, maybe you also need a dialogue regarding whether or not the user is sure that they want to delete an item ... 🤔
