### ISSUE TITLE
user story 5 / feat-navigation

### ISSUE THREAD

**Issue by alper92** [alper92/capstone-project#9]
## Value proposition

As an art enthusiast
I want to see a progress bar when scrolling down with my phone and buttons for each existing category, for all pieces as well as the newest art pieces
in order to navigate through the gallery and also see my progress

## Description
![Bildschirmfoto 2023-08-18 um 14 57 54](https://github.com/alper92/capstone-project/assets/83625276/5a7cb6cb-96eb-46da-b528-89c91da24dd5)

## Acceptance criteria

- [x] the dependencies of the progress bar are the window width and the window height
- [x] the progress bar should move to the right depending on the scroll process
- [x] the filters should apply also for new uploaded or changed pieces the admin created (it should work kind of like a navigation)

## Tasks

- [x] create a new branch `feat/navigation`
- [x] create the progress bar component and write the function to show the progress depending on the window height and width
- [x] create a component `navigation` which will filter through all art pieces and show the desired pictures

## Size

L

**Comment by KilianBau** [comment]
_the progress bar should only be visible for smartphone devices (window.width < iPhone SE)_ --> you don't need to add technical things in the acceptance criteria 

The tasks are not really detailed, I prefer to have more like an instruction for the coding, but still a good one 👍

**Comment by alper92** [comment]
> _the progress bar should only be visible for smartphone devices (window.width < iPhone SE)_ --> you don't need to add technical things in the acceptance criteria
> 
> The tasks are not really detailed, I prefer to have more like an instruction for the coding, but still a good one 👍

You are  right about the task area! I will improve that afterwords!
